@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "Author" <<LogicalModel>> [[StructureDefinition-Author.html]]
note right #PaleTurquoise [[ConceptMap-author2FHIR-eu-lab.html]]
Concept Map
endnote
class "Composition-eu-lab" <<Profile>> [[StructureDefinition-Composition-eu-lab.html]]
"Author" --> "Composition-eu-lab"
class "DiagnosticReport-eu-lab" <<Profile>> [[StructureDefinition-DiagnosticReport-eu-lab.html]]
"Author" --> "DiagnosticReport-eu-lab"
"Composition-eu-lab" -[hidden]-> "DiagnosticReport-eu-lab"
@enduml