@startuml

skinparam linetype ortho
scale 0.5


artifact "Bundle: Laboratory Report" as bundle
artifact "Composition: Laboratory Report" as composition
artifact "DiagnosticReport: Laboratory Report" as diagnosticReport
artifact "Observation Results: laboratory" as result
artifact "RelatedPerson: Animal" as animalSpecimen
artifact "Patient: Person" as humanPatient
artifact "Practitioner: Laboratory Report" as Practitioner
artifact "PractitionerRole: Laboratory Report" as PractitionerRole
artifact "ServiceRequest: Laboratory Order" as ServiceRequest
artifact "Specimen: Laboratory" as Specimen
artifact "Body structure: Laboratory" as bodyStructure
artifact "Substance: Specimen Additive Substance" as Substance

artifact Organization
artifact Encounter
artifact Location
artifact Provenance
artifact Coverage
artifact Device


url of bundle is  [[StructureDefinition-Bundle-eu-lab.html]]
url of composition is  [[StructureDefinition-Composition-eu-lab.html]]
url of diagnosticReport is  [[StructureDefinition-DiagnosticReport-eu-lab.html]]
url of result [[StructureDefinition-Observation-resultslab-eu-lab.html]]
url of humanPatient [[https://hl7.eu/fhir/base/StructureDefinition-patient-eu-core.html]]
url of animalSpecimen [[StructureDefinition-animal-specimen-eu-lab.html]]
url of Practitioner [[https://hl7.eu/fhir/base/StructureDefinition-practitioner-eu-core.html]]
url of PractitionerRole [[https://hl7.eu/fhir/base/StructureDefinition-practitionerRole-eu-core.html]]
url of ServiceRequest [[StructureDefinition-ServiceRequest-eu-lab.html]]
url of Specimen [[StructureDefinition-Specimen-eu-lab.html]]
url of Substance [[StructureDefinition-Substance-additive-eu-lab.html]]
url of bodyStructure [[https://hl7.eu/fhir/base/StructureDefinition-bodyStructure-eu-core.html]]

bundle o-- composition
bundle o-- diagnosticReport
bundle o-- result
bundle o-- humanPatient
bundle o-- animalSpecimen
bundle o-- composition
bundle o-- Practitioner
bundle o-- PractitionerRole
bundle o-- ServiceRequest
bundle o-- Specimen
bundle o-- Substance
bundle o-- bodyStructure
bundle o-- Organization
bundle o-- Encounter
bundle o-- Location
bundle o-- Provenance
bundle o-- Coverage
bundle o-- Device

composition --> result
composition --> animalSpecimen
composition --> humanPatient
composition --> Practitioner
composition --> PractitionerRole
composition --> ServiceRequest
composition --> Specimen
composition --> Location
composition --> Encounter


diagnosticReport --> composition
Specimen --> Substance
Specimen --> bodyStructure
PractitionerRole --> Practitioner
PractitionerRole --> Organization
result --> Device
ServiceRequest --> Coverage


@enduml