@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "LabReport" <<LogicalModel>> [[StructureDefinition-LabReport.html]]
note right #PaleTurquoise [[ConceptMap-labRpt2FHIR-eu-lab.html]]
Concept Map
endnote
class "DiagnosticReport-eu-lab" <<Profile>> [[StructureDefinition-DiagnosticReport-eu-lab.html]]
"LabReport" --> "DiagnosticReport-eu-lab"
class "Composition-eu-lab" <<Profile>> [[StructureDefinition-Composition-eu-lab.html]]
"LabReport" --> "Composition-eu-lab"
"DiagnosticReport-eu-lab" -[hidden]-> "Composition-eu-lab"
@enduml