@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "LegalAuthenticator" <<LogicalModel>> [[StructureDefinition-LegalAuthenticator.html]]
note right #PaleTurquoise [[ConceptMap-legalAuth2FHIR-eu-lab.html]]
Concept Map
endnote
class "Composition-eu-lab" <<Profile>> [[StructureDefinition-Composition-eu-lab.html]]
"LegalAuthenticator" --> "Composition-eu-lab"
@enduml