@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "Payer" <<LogicalModel>> [[StructureDefinition-Payer.html]]
note right #PaleTurquoise [[ConceptMap-payer2FHIR-eu-lab.html]]
Concept Map
endnote
class "ServiceRequest-eu-lab" <<Profile>> [[StructureDefinition-ServiceRequest-eu-lab.html]]
"Payer" --> "ServiceRequest-eu-lab"
class "Coverage" <<Profile>> [[http://hl7.org/fhir/StructureDefinition/Coverage]]
"Payer" --> "Coverage"
"ServiceRequest-eu-lab" -[hidden]-> "Coverage"
class "Patient-eu-lab" <<Profile>> [[StructureDefinition-Patient-eu-lab.html]]
"Payer" --> "Patient-eu-lab"
"Coverage" -[hidden]-> "Patient-eu-lab"
@enduml