@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "Recipient" <<LogicalModel>> [[StructureDefinition-Recipient.html]]
note right #PaleTurquoise [[ConceptMap-recipient2FHIR-eu-lab.html]]
Concept Map
endnote
class "information-recipient" <<Profile>> [[StructureDefinition-information-recipient.html]]
"Recipient" --> "information-recipient"
@enduml