@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "SpecimenLab" <<LogicalModel>> [[StructureDefinition-SpecimenLab.html]]
note right #PaleTurquoise [[ConceptMap-specimen2FHIR-eu-lab.html]]
Concept Map
endnote
class "Specimen-eu-lab" <<Profile>> [[StructureDefinition-Specimen-eu-lab.html]]
"SpecimenLab" --> "Specimen-eu-lab"
class "BodyStructure-eu-lab" <<Profile>> [[StructureDefinition-BodyStructure-eu-lab.html]]
"SpecimenLab" --> "BodyStructure-eu-lab"
"Specimen-eu-lab" -[hidden]-> "BodyStructure-eu-lab"
@enduml