@startuml
skinparam class {
    BackgroundColor<<LogicalModel>> #FFCC00
    BackgroundColor<<Profile>> #CCCCFF
}
skinparam linetype ortho
legend right
  | <#FFCC00> | Logical Model |
  | <#CCCCFF> | Profile |
endlegend
class "Subject" <<LogicalModel>> [[StructureDefinition-Subject.html]]
note right #PaleTurquoise [[ConceptMap-subject2FHIR-eu-lab.html]]
Concept Map
endnote
class "Patient-eu-lab" <<Profile>> [[StructureDefinition-Patient-eu-lab.html]]
"Subject" --> "Patient-eu-lab"
@enduml