ValueSet: LabCertifiedReferenceMaterialVS
Id: lab-certifiedRefMaterial-eu-lab
Title: "Laboratory Certified Reference Material"
Description: "List of the coded concepts describing the certified reference material used for the calibration, typically used when the unit of the result is UCUM [IU]."

* insert JCTLMCopyrightForVS
* insert SetFmmandStatusRule ( 2, trial-use)

* $nibsc#06/140 "Pertussis antiserum (human), anti-PT IgG, Lyophilized, 335 IU and anti-PT IgA 65 IU / ampoule; anti-FHA IgG 130 IU and anti-FHA IgA 65 IU / ampoule; anti-69K IgG 65 IU and anti-PT IgA 42 IU / ampoule"
* $nibsc#00/588 "Hepatitis B virus surface antigen, subtype adw2, genotype A, Lyophilized, 33 IU/vial."
* $nibsc#01/600 "Anti-toxoplasma serum (IgG), Lyophilized, 20 IU / ampoule."
* $nibsc#01/608 "Low Molecular Weight Heparin"
* $nibsc#02/150 "Blood Coagulation Factor VIII and Von Willebrand Factor in Plasma, Human"
* $nibsc#02/206 "Blood coagulation factor XIII, Lyophilized, Activity 0.91 IU/ampoule; Antigen 0.93 IU/ampoule"
* $nibsc#02/342 "Protein C, Lyophilized, 0.85 IU/ampoule (function), 0.84 IU/ampoule (antigen)."
* $nibsc#03/116 "Blood coagulation factor V, Lyophilized, 0.74 IU of Factor V:C per ampoule"
* $nibsc#03/228 "Protein S, Lyophilized, 0.83 IU/ampoule (total antigen), 0.81 IU/ampoule (free antigen), 0.77 IU/ampoule (function)."
* $nibsc#04/102 "Blood coagulation factor XI, plasma human, Lyophilized., 0.86 International Units per ampoule"
* $nibsc#07/164 "Anti-hepatitis B immunoglobulin, Lyophilized, 100 IU/ampoule"
* $nibsc#07/316 "Blood coagulation factor VIII and von Willebrand factor, Lyophilized, Factor VIII: C 0.68 IU/ amp; Factor VIII:Antigen 1.04 IU/ amp; VWF:Antigen 1.00 IU/ amp; VWF:Ristocetin cofactor 0.87 IU/amp; VWF:Collagen binding 1.03 IU/amp; VWFpp 1.03 IU/amp"
* $nibsc#07/364 "Chorionic gonadotrophin, Lyophilized 179 International Units or 0.39 nmol per ampoule for calibration of immunossays, and 162 International Units per ampoule for calibration of biossay, ,"
* $nibsc#08/204 "Thyroid-stimulating antibody, Lyophilized, 0.113 IU / ampoule."
* $nibsc#08/258 "Antithrombin, Lyophilized, Functional potency - 0.95 IU/ampoule, Antigenic potency - 0.96 IU/ampoule"
* $nibsc#08/266 "Sex hormone binding globulin (SHBG), Lyophilized, 180 IU / ampoule."
* $nibsc#09/162 "Human cytomegalovirus DNA, Lyophilized, 5,000,000 IU/vial."
* $nibsc#09/172 "Blood coagulation factors II, VII, IX, X, Lyophilized, 0.89 IU (factor II), 0.99 IU (factor VII), 0.9 IU (factor IX), 0.89 IU (factor X) / ampoule."
* $nibsc#09/260 "Epstein Barr virus DNA, Lyophilized, 5,000,000 IU/ml"
* $nibsc#09/264 "Fibrinogen, Lyophilized, 2.7 mg/ampoule"
* $nibsc#10/152 "HIV-1 RNA, Lyophilized, 185,000 IU/ml (5.27 log10 IU/ml)"
* $nibsc#10/262 "Diphtheria Antitoxin Human IgG, Lyophilized, 2 IU / ampoule"
* $nibsc#10/264 "Hepatitis B virus DNA, Lyophilized., 850,000 IU / vial."
* $nibsc#11/176 "Heparin, low molecular weight, Lyophilized, Anti-Xa: 1068 IU/ampoule, Anti-Iia: 342 IU/ampoule"
* $nibsc#11/234 "Human serum immunoglobulin E, Lyophilized, 13,500 IU/mL"
* $nibsc#11/700 "Erythropoietin, rDNA-derived, Lyophilized, 1,650 IU / ampoule."
* $nibsc#12/252 "A Disintegrin And Metalloprotease with ThromboSpondin type 1 motifs 13 (ADAMTS13), plasma, Lyophilized., Function: 0.91 IU/ampoule Antigen: 0.92 IU/ampoule"
* $nibsc#14/114 "JC polyomavirus DNA, Lyophilized., 7.0 log10 IU/ mL"
* $nibsc#14/212 "BK polyomavirus DNA, Lyophilized., 7.2 log10 IU/ mL"
* $nibsc#15/180 "Factor XI, plasma, human, Lyophilized, Functional activity: 0.71 IU per ampoule, Antigen: 0.78 IU per ampoule"
* $nibsc#16/368 "HSV-1"
* $nibsc#17/100 "Prostate Specific Antigen (human)(total: PSA-ACT + free PSA)"
* $nibsc#17/122 "HSV-2"
* $nibsc#66/304 "Insulin, human, for immunoassay, Lyophilized, 3 IU / ampoule."
* $nibsc#67/086 "Human serum immunoglobulins G, A, and M (IgG, IgA and IgM), Lyophilized, 100 IU IgG, 100 IU IgA and 100 IU IgM/ampoule."
* $nibsc#67/343 "Erythropoietin, human, urinary, Lyophilized, 10 IU / ampoule."
* $nibsc#68/356 "Renin, human, Lyophilized, 0.1 IU / ampoule."
* $nibsc#69/194 "Glucagon, porcine, Lyophilized, 1.49 IU / ampoule."
* $nibsc#73/545 "Placental lactogen, human, for immunoassay, Lyophilized, 0.000 850 IU / ampoule."
* $nibsc#73/601 "Carcinoembryonic antigen (CEA), Lyophilized, 100 IU/ampoule"
* $nibsc#75/551 "Chorionic gonadotrophin, beta subunit, human, for immunoassay, Lyophilized, 70 IU / ampoule."
* $nibsc#75/569 "Chorionic gonadotrophin, alpha subunit, human, for immunoassay, Lyophilized, 70 IU / ampoule."
* $nibsc#75/589 "Chorionic gonadotrophin, human, Lyophilized, 650 IU / ampoule."
* $pei#7657/12 "Hepatitis D virus RNA, Lyophilized, 575,000 IU/mL"
* $nibsc#78/554 "Luteinizing hormone, human, pituitary, alpha subunit, Lyophilized, 10 IU / ampoule."
* $nibsc#78/556 "Luteinizing hormone, human, pituitary, beta subunit, Lyophilized, 10 IU / ampoule."
* $nibsc#79/500 "Parathyroid hormone, human, for immunoassay, Lyophilized, 0.1 IU / ampoule."
* $nibsc#80/505 "Human growth hormone, pituitary, Lyophilized, 4.4 IU / ampoule."
* $nibsc#80/552 "Luteinizing hormone, human, pituitary, Lyophilized, 35 IU / ampoule."
* $nibsc#81/565 "Thyroid stimulating hormone, human, for immunoassay, Lyophilized, 11.5 x -3 log 10 IU / ampoule."
* $nibsc#82/585 "Anti-poliovirus serum (Types 1, 2, 3), Lyophilized, 11 IU/ampoule (Type 1), 32 IU/ampoule (Type 2), 3 IU/ampoule (Type 3)"
* $nibsc#82/587 "Interferon Gamma (Human, Leukocyte derived)"
* $nibsc#83/501 "Beta-thromboglobulin, Lyophilized, 500 IU/ampoule."
* $nibsc#83/505 "Platelet factor 4, Lyophilized, 400 IU/ampoule"
* $nibsc#83/575 "Follicle stimulating hormone, human, pituitary, Lyophilized, 80 IU / ampoule."
* $nibsc#84/500 "Prolactin, human, Lyophilized., 0.053 IU / ampoule."
* $nibsc#85/506 "C-reactive protein, Lyophilized, 0.049 IU/ampoule"
* $nibsc#85/669 "Atrial natriuretic factor, human, Lyophilized, 2.5 IU / ampoule."
* $nibsc#88/638 "Thyroxine-binding globulin, Lyophilized, 30 IU / ampoule."
* $nibsc#89/620 "Calcitonin, human, Lyophilized, 17.5 IU / ampoule."
* $nibsc#91/554 "Insulin-like growth factor I for bioassay, Lyophilized, 150 IU / ampoule."
* $nibsc#91/624 "Inhibin A, human, recombinant, Lyophilized, 150,000 IU / ampoule."
* $nibsc#92/510 "Follicle stimulating hormone, human, recombinant for immunoassay, Lyophilized, 60 IU / ampoule."
* $nibsc#92/654 "Plasminogen-Activator Inhibitor 1 (PAI-1), Lyophilized, Tissueplasminogen-activator: 27.5 IU of neutralising activity/ampoule. Urinary-plasminogen-activator: 7 IU of neutralising activity/ampoule."
* $nibsc#94/572 "Ferritin, recombinant, Lyophilized, 6.3 μg/ampoule"
* $nibsc#96/670 "Prostate specific antigen (90:10), Lyophilized, 1 μg total PSA per vial."
* $nibsc#97/550 "Islet cell antibodies, Lyophilized, 20 units/ampoule of islet cell antibodies; 100 units/ampoule of anti-GAD65; 100 units/ampoule of anti-IA-2."
* $nibsc#97/646 "Anti-Hepatitis A Immunoglobulin, Human (W1041) WHO International Standard"
* $nibsc#98/574 "Somatropin (rDNA-derived human growth hormone), Lyophilized, 1.95 mg protein / ampoule."
* $nibsc#AFP "Alphafoetoprotein, Lyophilized, 100,000 IU / ampoule."
* $niaid#Gxg01-902535 "Interferon gamma, human, recombinant, Lyophilized, 80,000 IU / ampoule."
* $nibsc#RAI "Anti-rabies immunoglobulin, Lyophilized, 30 IU/ampoule"
* $nibsc#rTF/16 "Thromboplastin, Human, Recombinant, Plain 5th International Standard 2016."
* $nibsc#RUBI-1-94 "Anti-rubella immunoglobulin, Lyophilized, 1,600 IU/vial"
* $nibsc#W1066 "Rheumatoid arthritis serum, Lyophilized, 100 IU/ampoule"
